apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
  - name: http
    port: 8761
    targetPort: 8761
#    nodePort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image:
        ports:
        - containerPort: 8761